# Generated by Django 5.0.6 on 2024-07-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_response_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='anydesk_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('suporte', 'Suporte'), ('facilites', 'Facilites'), ('rh', 'Recursos Humanos'), ('outro', 'Outro')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
