# Generated by Django 5.0.6 on 2024-07-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
    ]
